'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const { once } = require('node:events');
const { createServer } = require('../src/server');

test('onboarding routes serve signup, setup, auth config, and the local Supabase client', async () => {
  const server = createServer({ runtime: {} });
  server.listen(0, '127.0.0.1');
  await once(server, 'listening');
  const { port } = server.address();
  const origin = `http://127.0.0.1:${port}`;
  try {
    const signup = await fetch(`${origin}/signup`);
    assert.equal(signup.status, 200);
    const signupHtml = await signup.text();
    assert.match(signupHtml, /Start free/);
    assert.match(signupHtml, /Continue with Google/);
    assert.match(signupHtml, /id="emailToggleButton"/);
    assert.match(signupHtml, /id="emailForm" hidden/);
    assert.match(signupHtml, /Enter your email and password to receive a verification code\./);
    assert.match(signupHtml, /Send verification code/);
    assert.match(signupHtml, /If you don't see the email, check your spam folder\. Enter the code below\./);
    assert.match(signupHtml, /aria-describedby="otpInstructions"/);
    assert.doesNotMatch(signupHtml, /id="otpBack"/);
    assert.match(signupHtml, /Security data stays on your infrastructure/);

    const cliLogin = await fetch(`${origin}/cli-login`);
    assert.equal(cliLogin.status, 200);
    const cliLoginHtml = await cliLogin.text();
    assert.match(cliLoginHtml, /Authorize Lookout CLI/);
    assert.match(cliLoginHtml, /Verification code from the CLI/);
    assert.match(cliLoginHtml, /id="cliVerificationFields"/);
    assert.match(cliLoginHtml, /id="cliLoginCommand" hidden/);
    assert.match(cliLoginHtml, /<code>lookout login<\/code>/);
    assert.match(cliLoginHtml, /id="cliCopyCommand"/);
    assert.doesNotMatch(cliLoginHtml, /Technical details|cliTechnical/);
    const cliLoginScript = await fetch(`${origin}/cli-login.js`).then((response) => response.text());
    assert.match(cliLoginScript, /Selected VMs/);
    assert.match(cliLoginScript, /Login session expired/);
    assert.match(cliLoginScript, /This CLI login request is unavailable or expired\. Please run lookout login again/);
    assert.match(cliLoginScript, /verificationFields\.hidden = true/);
    assert.match(cliLoginScript, /loginCommand\.hidden = !expired/);
    assert.match(cliLoginScript, /navigator\.clipboard\.writeText\('lookout login'\)/);
    assert.match(cliLoginScript, /cli-expired-card/);
    assert.match(cliLoginScript, /cli-expired-message/);
    assert.doesNotMatch(cliLoginScript, /installation_scope_digest|deployment_key_fingerprint|cliTechnical/);

    const setup = await fetch(`${origin}/setup`);
    assert.equal(setup.status, 200);
    const setupHtml = await setup.text();
    assert.match(setupHtml, /id="setupInstructions"/);
    assert.match(setupHtml, /Designed to protect cloud-hosted Linux VMs/);
    assert.match(setupHtml, /class="setup-scope-note">Not designed for local machines\.<\/p>/);
    assert.match(setupHtml, /Install Lookout on Linux VMs I approve/);
    assert.match(setupHtml, /Ask which private network I want to monitor/);
    assert.match(setupHtml, /If you don’t have access, ask how to access it/);
    assert.match(setupHtml, /scan the VMs in that network, give me the list/);
    assert.match(setupHtml, /exhaustively verify administrative access to each selected VM/);
    assert.match(setupHtml, /Report Needs access for inaccessible VMs/);
    assert.match(setupHtml, /lookout vm add --name NAME --address PRIVATE_IP/);
    assert.match(setupHtml, /--ssh-host SSH_HOST/);
    assert.match(setupHtml, /access check used a hostname or SSH alias, using that exact value/);
    assert.match(setupHtml, /https:\/\/app\.devlookout\.com\/cli\/install\.sh/);
    assert.match(setupHtml, /delete only that exact file with `unlink` in a separate command/);
    assert.match(setupHtml, /Never use `rm`, globs, recursive deletion, or a compound command for cleanup/);
    assert.match(setupHtml, /lookout vm central NAME/);
    assert.match(setupHtml, /existing SSH configuration/);
    assert.match(setupHtml, /For security, I’ll let you complete the browser authentication and verification-code process yourself/);
    assert.match(setupHtml, /\$HOME\/\.local\/bin\/lookout login/);
    assert.match(setupHtml, /\$env:LOCALAPPDATA\\Lookout\\bin\\lookout\.cmd/);
    assert.match(setupHtml, /When finished, reply `done`/);
    assert.match(setupHtml, /End your turn and wait/);
    assert.match(setupHtml, /After I reply `done`, run `lookout install` and wait for it to finish/);
    assert.doesNotMatch(setupHtml, /lookout prepare/);
    assert.doesNotMatch(setupHtml, /central VM, scope value, deployment-key fingerprint/);
    assert.match(setupHtml, /run `lookout diagnose` and fix the reported problem/);
    assert.match(setupHtml, /lookout install --retry/);
    assert.match(setupHtml, /resumes a saved deployment when possible and otherwise starts a new installation attempt/);
    assert.match(setupHtml, /If still blocked, run `lookout report`/);
    assert.match(setupHtml, /`lookout report submit SURVEY_FILE`/);
    const setupPrompt = setupHtml.match(/id="setupInstructions">([\s\S]*?)<\/code>/)?.[1] || '';
    assert.doesNotMatch(setupPrompt, /\*\*/);
    assert.doesNotMatch(setupPrompt, /run it with `sh`, delete it/);
    assert.ok(setupPrompt.indexOf('Ask which private network') < setupPrompt.indexOf('scan the VMs'));
    assert.ok(setupPrompt.indexOf('scan the VMs') < setupPrompt.indexOf('ask which VMs'));
    assert.ok(setupPrompt.indexOf('administrative access') < setupPrompt.indexOf('lookout vm add'));
    assert.ok(setupPrompt.indexOf('lookout vm add') < setupPrompt.indexOf('lookout vm central'));
    assert.ok(setupPrompt.indexOf('$HOME/.local/bin/lookout login') < setupPrompt.indexOf('lookout install'));
    assert.doesNotMatch(setupHtml, /LOOKOUT_SETUP_TOKEN|LOOKOUT_SUPPORT_TOKEN_VALUE|lookout_setup_token/);
    assert.match(setupHtml, /id="setupCard">/);
    assert.match(setupHtml, /id="copySetupButton">Copy prompt/);
    assert.doesNotMatch(setupHtml, /Select (?:AWS|DigitalOcean)|Choose a provider/);
    assert.doesNotMatch(setupHtml, /setupPairingForm|setupPairingCode|pairInstallerButton|approvePairingButton|verification phrase/i);
    assert.doesNotMatch(setupHtml, /Connect an alert channel|id="notificationInstructions"|copyNotificationInstructionsButton/);
    assert.match(setupHtml, /id="settingsView"/);
    assert.doesNotMatch(setupHtml, /<h2>Settings<\/h2>|Account, notifications, and data\./);
    assert.doesNotMatch(setupHtml, /Manage your Lookout account and access/);
    assert.match(setupHtml, /id="signOutButton">Sign out/);
    assert.match(setupHtml, /id="accountName"/);
    assert.match(setupHtml, /id="accountAvatarImage"/);
    assert.doesNotMatch(setupHtml, /id="accountLogin"/);
    assert.match(setupHtml, /id="deleteAccountDisclosure"/);
    assert.match(setupHtml, /<h3>Delete permanently\?<\/h3>/);
    assert.match(setupHtml, /id="uninstallInstructions"/);
    assert.match(setupHtml, /sudo \/usr\/local\/sbin\/lookout-uninstall --purge --yes/);
    assert.match(setupHtml, /Read ~\/\.lookout\/security-observability-config\.json, falling back to ~\/\.lookout\/fleet\.json only if absent/);
    assert.match(setupHtml, /For an interrupted installation, read ~\/\.lookout\/install\/onboarding-state\.json, falling back to onboarding-resume\.json only if absent/);
    assert.match(setupHtml, /Try a recorded management transport when present/);
    assert.match(setupHtml, /Do not run cloud inventory, scan networks, rediscover VMs, or probe unrelated hosts/);
    assert.match(setupHtml, /Continue only if its deploymentId matches the saved deployment/);
    assert.match(setupHtml, /Uninstall collectors first and the central VM last/);
    assert.match(setupHtml, /On every verified VM, run only/);
    assert.match(setupHtml, /Do not manually remove Lookout services or files/);
    assert.match(setupHtml, /SaaS now shows this deployment as uninstalled/);
    assert.match(setupHtml, /No SaaS confirmation is required if a central VM was never installed/);
    assert.match(setupHtml, /After every saved VM is resolved as uninstalled or not installed for this deployment, and any required SaaS confirmation succeeds/);
    assert.match(setupHtml, /Retain the local state if any VM, uninstall, or required SaaS confirmation remains unresolved/);
    assert.match(setupHtml, /id="copyUninstallInstructionsButton">Copy agent instruction/);
    assert.match(setupHtml, /id="deleteAccountButton">Delete account permanently/);
    assert.match(setupHtml, /id="mapEmptyTitle">Install Lookout on your first system/);
    assert.match(setupHtml, /id="mapEmptyDetail"/);
    assert.match(setupHtml, /Install Lookout on your first system/);
    assert.match(setupHtml, /href="\/setup" data-view="setup" id="mapEmptyAction">Continue setup/);
    assert.doesNotMatch(setupHtml, /TAILSCALE_API_TOKEN|survey-tailscale|survey-declaration/);
    assert.match(setupHtml, /id="setupPhase"/);
    assert.match(setupHtml, /id="setupEta"/);
    assert.match(setupHtml, /id="setupData"/);
    assert.match(setupHtml, /id="setupProgress" hidden>[\s\S]*INSTALLATION IN PROGRESS[\s\S]*id="setupEta"/);
    assert.match(setupHtml, /id="resetSetupButton" hidden>Try again/);
    assert.ok(setupHtml.indexOf('id="setupProgress"') < setupHtml.indexOf('class="setup-heading"'));
    assert.doesNotMatch(setupHtml, /Replace this placeholder/);
    assert.match(setupHtml, />Log search</);
    assert.match(setupHtml, /href="https:\/\/docs\.devlookout\.com" data-abbr="D" target="_blank" rel="noopener noreferrer">Docs<\/a>/);
    assert.doesNotMatch(setupHtml, />Activity<|ARCHITECTURE|Settings Manage your Lookout account and access/);

    for (const pathname of ['/map', '/assets', '/alerts', '/rules', '/logs', '/settings']) {
      const page = await fetch(`${origin}${pathname}`);
      assert.equal(page.status, 200);
      assert.match(await page.text(), /id="overviewView"/);
    }

    const config = await fetch(`${origin}/auth/config.js`);
    assert.equal(config.status, 200);
    assert.match(config.headers.get('content-type'), /text\/javascript/);
    assert.match(await config.text(), /window\.__LOOKOUT_AUTH__/);

    const client = await fetch(`${origin}/vendor/supabase.js`);
    assert.equal(client.status, 200);
    assert.match(client.headers.get('content-type'), /text\/javascript/);
    assert.ok((await client.arrayBuffer()).byteLength > 1000);

    const app = await fetch(`${origin}/app.js`);
    assert.equal(app.status, 200);
    const appSource = await app.text();
    const api = await fetch(`${origin}/api.js`);
    assert.equal(api.status, 200);
    const apiSource = await api.text();
    const stylesheet = await fetch(`${origin}/styles.css`);
    assert.equal(stylesheet.status, 200);
    const styles = await stylesheet.text();
    assert.match(appSource, /document\.querySelector\('#setupCard'\)\.hidden = false/);
    assert.match(appSource, /copySetupValue\(text, document\.querySelector\('#copySetupButton'\)/);
    assert.match(appSource, /state\.user\.displayName \|\| state\.user\.email/);
    assert.doesNotMatch(appSource, /querySelector\('#accountLogin'\)/);
    assert.match(appSource, /session\.user\.user_metadata\?\.full_name/);
    assert.match(appSource, /Log search is only available with cloud log storage/);
    assert.match(appSource, /function hostedTopology/);
    assert.match(appSource, /relation: 'member_of'/);
    assert.match(apiSource, /if \(!snapshotRequest\)/);
    assert.match(apiSource, /snapshotRequest = get/);
    assert.match(appSource, /Reason \(optional\)/);
    assert.doesNotMatch(appSource, /name="reason"[^>]*required/);
    assert.doesNotMatch(appSource, /Open \+ to fix|No alerts have been generated|The backend/);
    assert.match(appSource, /Lookout is already set up for this account/);
    assert.match(appSource, /history\[replace \? 'replaceState' : 'pushState'\]/);
    assert.match(appSource, /window\.addEventListener\('popstate'/);
    assert.match(appSource, /Estimated time remaining: 5-10 minutes/);
    assert.match(appSource, /Estimated time remaining: 2-5 minutes/);
    assert.match(appSource, /Estimated time remaining: under 2 minutes/);
    assert.match(appSource, /progress\.hidden = false/);
    assert.match(appSource, /return `Discovered \$\{total\} VM\$\{total === 1 \? '' : 's'\}`/);
    assert.match(appSource, /emptyTitle\.textContent = needsAccess \? 'Setup needs access' : mapSetupPhaseText/);
    assert.match(appSource, /bannerTitle'\)\.textContent = state\.setupStatus === 'needs_access' \? 'Setup needs access\.' : mapSetupPhaseText/);
    assert.match(appSource, /Data will appear here automatically as systems connect/);
    assert.match(appSource, /emptyEyebrow\.textContent = needsAccess \? 'ACTION REQUIRED' : 'INSTALLING'/);
    assert.match(appSource, /LookoutApi\.activeSetup\(\)/);
    assert.match(appSource, /Setup failed after selecting \$\{total\} VM/);
    assert.doesNotMatch(appSource, /Installation stopped before completion/);
    assert.doesNotMatch(appSource, /Review the installer output for the failure that stopped this installation/);
    assert.match(appSource, /Try again with the same setup token\./);
    assert.match(styles, /\[data-status="failed"\] \.setup-progress-data \{ border-bottom:[^}]+border-top: 0; margin-top: 5px; padding: 0 0 13px;/);
    assert.doesNotMatch(appSource, /support ticket|support@devlookout\.com/i);
    assert.match(appSource, /if \(status\.status === 'failed'\) return/);
    assert.ok(appSource.indexOf('LookoutApi.activeSetup()') < appSource.indexOf("if (!validStoredSetup(value)) value = await LookoutApi.createSetupSession()"));
    assert.match(appSource, /deployment && deployment\.status !== 'uninstalled'\)[\s\S]*sessionStorage\.removeItem\(SETUP_SESSION_STORAGE\)/);
    assert.match(appSource, /This installation was restored from Lookout and is still running/);
    assert.match(appSource, /sessionStorage\.removeItem\(SETUP_SESSION_STORAGE\);[\s\S]*setupInitialization = null;[\s\S]*ensureSetupSession\(\)/);
    assert.match(appSource, /error\?\.status === 404[\s\S]*sessionStorage\.removeItem\(SETUP_SESSION_STORAGE\)/);
    assert.match(appSource, /const setup = state\.setup;[\s\S]*state\.setup\?\.session_id !== setup\.session_id/);
    assert.match(appSource, /clearTimeout\(setupPollTimer\);[\s\S]*setupPollTimer = null/);
    assert.match(apiSource, /error\.status = response\.status/);
    assert.match(apiSource, /resetSetup: \(\) => request\('\/v1\/setup-sessions\/reset'/);
    assert.doesNotMatch(appSource, /Could not create a setup token\. An account can have only one active network/);
    assert.match(appSource, /Lookout is uninstalled\./);
    assert.match(appSource, /Nothing is installed or tracked anymore/);
  } finally {
    server.close();
    await once(server, 'close');
  }
});
