'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const repository = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(repository, file), 'utf8');

test('Fumadocs root keeps the main redirect and exposes visible support MCP setup above install', () => {
  const home = read('docs/app/(home)/page.tsx');
  const install = read('docs/app/install/page.tsx');
  const commands = read('docs/components/agent-command-links.tsx');
  assert.match(home, /redirect\('\/install'\)/);
  assert.match(install, /<AgentCommandLinks \/>/);
  assert.match(commands, /Settings &gt; Support AI/);
  assert.match(commands, /Configure \$\{supportMcpUrl\} as a Streamable HTTP remote MCP server/);
  assert.match(commands, /Lookout Settings at https:\/\/app\.devlookout\.com\/settings by opening Support AI and using the copy button under the Support MCP setup preview/);
  assert.match(commands, /trusted local coding agent/);
  assert.match(commands, /Bearer token authentication, not OAuth/);
  assert.match(commands, /Extract the Bearer token from the copied setup/);
  assert.doesNotMatch(commands, /Agent docs/);
  assert.doesNotMatch(commands, /https:\/\/docs\.devlookout\.com\/llms\.txt/);
  assert.match(commands, />Support MCP setup</);
  assert.match(commands, /https:\/\/app\.devlookout\.com\/support\/mcp/);
  assert.match(commands, /LOOKOUT_SUPPORT_TOKEN environment variable/);
  assert.match(commands, /Do not open the MCP URL in a browser/);
  assert.match(commands, /run an OAuth login/);
  assert.match(commands, /ask me to paste the token by itself into chat/);
  assert.match(commands, /navigator\.clipboard\.writeText/);
  assert.match(commands, /<button/);
  assert.match(commands, /<pre><code>\{supportInstruction\}<\/code><\/pre>/);
  assert.doesNotMatch(commands, /<code>\{supportMcpUrl\}<\/code>/);
  assert.doesNotMatch(commands, /href=/);
  assert.ok(install.indexOf('<DocsDescription>') < install.indexOf('<AgentCommandLinks />'));
  assert.ok(install.indexOf('<AgentCommandLinks />') < install.indexOf('<DocsBody>'));
  assert.doesNotMatch(install, /llms-full|safe prompt|only MCP connection/i);
  const source = read('docs/lib/source.ts');
  const generated = read('docs/lib/agent-content.ts');
  assert.match(source, /includeProcessedMarkdown:\s*true/);
  assert.match(generated, /source\.getPages\(\)/);
  assert.match(generated, /page\.data\.getText\('processed'\)/);
  const pages = JSON.parse(read('docs/content/docs/meta.json')).pages;
  assert.ok(pages.includes('install'));
  assert.ok(pages.includes('!privacy'));
  assert.ok(!pages.includes('agent-support'));
  assert.equal(fs.existsSync(path.join(repository, 'docs/content/docs/agent-support.mdx')), false);
  const sharedLayout = read('docs/lib/layout.shared.tsx');
  const privacyLayout = read('docs/app/privacy/layout.tsx');
  assert.match(sharedLayout, /<Link className="docs-sidebar-footer-link" href="\/privacy">Privacy Policy<\/Link>/);
  assert.match(privacyLayout, /layout\.module\.css/);
  assert.match(privacyLayout, /containerProps=\{\{ className: styles\.layout \}\}/);
});

test('install help and privacy notice describe safe MCP and retention behavior without obsolete docs origins', () => {
  const install = read('docs/content/docs/install.mdx');
  const mdx = read('docs/components/mdx.tsx');
  const privacy = read('docs/content/docs/privacy.mdx');
  assert.match(install, /For guided troubleshooting, connect your coding agent to the Lookout Support AI Agent\./);
  assert.match(install, /https:\/\/app\.devlookout\.com\/settings/);
  assert.match(install, /click the copy button under the \*\*Support MCP setup\*\* preview/);
  assert.match(install, /trusted local coding agent/);
  assert.match(install, /https:\/\/app\.devlookout\.com\/support\/mcp/);
  assert.match(install, /\*\*Streamable HTTP\*\* MCP server/);
  assert.match(install, /\*\*Bearer token\*\*/);
  assert.match(install, /does not support OAuth/);
  assert.match(install, /Do not run an OAuth login for this server/);
  assert.match(install, /HTTP `401`, which is expected/);
  assert.match(install, /secret Support token/);
  assert.match(install, /ask_lookout_support/);
  assert.match(install, /check_lookout_support/);
  assert.doesNotMatch(install, /Show|Copy token|bearer_token_env_var|LOOKOUT_SUPPORT_TOKEN/);
  assert.match(install, /<AgentCommandLinks compact \/>/);
  assert.match(mdx, /AgentCommandLinks/);
  assert.doesNotMatch(install, /\/agent-support/);
  for (const expected of ['Supabase', 'OpenAI', 'Resend', '90 days', 'support staff', 'Deleting the Lookout account']) assert.match(privacy, new RegExp(expected));
  const docsFiles = fs.readdirSync(path.join(repository, 'docs/content/docs')).filter((file) => file.endsWith('.mdx')).map((file) => read(`docs/content/docs/${file}`)).join('\n');
  assert.doesNotMatch(docsFiles, /https:\/\/devlookout\.com\/(?:docs|llms)/);
});
