'use strict';

const { attachFrameworkMappings } = require('./framework-mappings');

const analytics = [
  { id: 'auth-failure-burst', behavior: 'credential-abuse', version: '1.0.0', title: 'Repeated authentication failures from one source', kind: 'threshold', severity: 'high', enabled: true, requirements: { all: ['authentication'], optional: ['network_flow'] }, selector: { class: 'authentication', outcome: 'failure' }, threshold: 12, windowSeconds: 300, groupBy: ['sourceEndpoint.id'], exclusions: [] },
  { id: 'auth-source-many-identities', behavior: 'credential-abuse', version: '1.0.0', title: 'Authentication source targets many identities', kind: 'threshold', severity: 'high', enabled: true, requirements: { all: ['authentication'] }, selector: { class: 'authentication', outcome: 'failure', 'actor.id': { exists: true } }, threshold: 6, distinctBy: 'actor.id', windowSeconds: 600, groupBy: ['sourceEndpoint.id'], exclusions: [] },
  { id: 'auth-identity-many-targets', behavior: 'credential-abuse', version: '1.0.0', title: 'Identity authenticates to many targets', kind: 'threshold', severity: 'medium', enabled: true, requirements: { all: ['authentication'] }, selector: { class: 'authentication', outcome: 'success', 'actor.id': { exists: true } }, threshold: 8, distinctBy: 'destinationEndpoint.id', windowSeconds: 900, groupBy: ['actor.id'], exclusions: [] },
  { id: 'auth-failure-then-success', behavior: 'credential-abuse', version: '1.0.0', title: 'Authentication succeeds after failure', kind: 'sequence', severity: 'medium', enabled: true, requirements: { all: ['authentication'] }, sequence: [{ class: 'authentication', outcome: 'failure' }, { class: 'authentication', outcome: 'success' }], windowSeconds: 300, groupBy: ['sourceEndpoint.id', 'destinationEndpoint.id', 'actor.id'], exclusions: [] },
  { id: 'remote-auth-then-execution', behavior: 'lateral-movement', version: '1.1.0', title: 'Remote authentication followed by execution', kind: 'sequence', severity: 'critical', enabled: true, requirements: { all: ['authentication', 'process_execution'], optional: ['network_flow'] }, sequence: [{ class: 'authentication', outcome: 'success' }, { class: 'process_activity', activity: 'start', 'attributes.parentType': 'remote_session' }], windowSeconds: 120, groupBy: ['sourceEndpoint.id', 'destinationEndpoint.id'], exclusions: [] },
  { id: 'remote-auth-then-privilege-use', behavior: 'privilege-escalation', version: '1.0.0', title: 'Remote authentication followed by privileged execution', kind: 'sequence', severity: 'critical', enabled: true, requirements: { all: ['authentication', 'privilege_use'] }, sequence: [{ class: 'authentication', activity: 'remote_logon', outcome: 'success' }, { class: 'privilege_use', activity: { in: ['sudo', 'change_process_identity'] } }], windowSeconds: 300, groupBy: ['actor.id', 'destinationEndpoint.id'], exclusions: [] },
  { id: 'remote-auth-then-account-created', behavior: 'persistence', version: '1.0.0', title: 'Remote authentication followed by local account creation', kind: 'sequence', severity: 'critical', enabled: true, requirements: { all: ['authentication', 'identity_inventory'] }, sequence: [{ class: 'authentication', activity: 'remote_logon', outcome: 'success' }, { class: 'account_management', activity: 'create', 'attributes.loginEnabled': true }], windowSeconds: 900, groupBy: ['destinationEndpoint.id'], exclusions: [] },
  { id: 'remote-auth-then-persistence', behavior: 'persistence', version: '1.0.0', title: 'Remote authentication followed by persistent service creation', kind: 'sequence', severity: 'critical', enabled: true, requirements: { all: ['authentication', 'service_inventory'] }, sequence: [{ class: 'authentication', activity: 'remote_logon', outcome: 'success' }, { class: 'service_activity', activity: { in: ['create', 'enable'] } }], windowSeconds: 900, groupBy: ['destinationEndpoint.id'], exclusions: [] },
  { id: 'remote-auth-then-listener-created', behavior: 'service-exploitation', version: '1.0.0', title: 'Remote authentication followed by a new exposed listener', kind: 'sequence', severity: 'critical', enabled: true, requirements: { all: ['authentication', 'network_listener'] }, sequence: [{ class: 'authentication', activity: 'remote_logon', outcome: 'success' }, { class: 'exposure_activity', activity: 'listener_create', 'attributes.exposureScope': { in: ['all_interfaces', 'host_interface'] } }], windowSeconds: 900, groupBy: ['destinationEndpoint.id'], exclusions: [] },
  { id: 'service-spawned-command-interpreter', behavior: 'service-exploitation', version: '1.0.0', title: 'Service spawned a command interpreter', kind: 'event', severity: 'critical', enabled: true, requirements: { all: ['process_execution'], optional: ['http_transaction'] }, selector: { class: 'process_activity', activity: 'start', 'attributes.parentType': 'network_service', 'attributes.processType': 'command_interpreter' }, exclusions: [] },
  { id: 'telemetry-disabled', behavior: 'defense-evasion', version: '1.0.0', title: 'Telemetry source disabled', kind: 'event', severity: 'high', enabled: true, requirements: { all: ['sensor_health'] }, selector: { category: 'health', class: 'sensor_activity', activity: { in: ['disable', 'stop'] } }, exclusions: [] },
  { id: 'security-log-cleared', behavior: 'defense-evasion', version: '1.0.0', title: 'Security log cleared or truncated', kind: 'event', severity: 'high', enabled: true, requirements: { all: ['configuration_change'] }, selector: { category: 'configuration', class: 'log_activity', activity: { in: ['clear', 'truncate', 'delete'] } }, exclusions: [] },
  { id: 'security-policy-changed', behavior: 'control-modification', version: '1.0.0', title: 'Security policy changed', kind: 'event', severity: 'medium', enabled: true, requirements: { all: ['configuration_change'] }, selector: { category: 'configuration', class: 'network_policy_activity', activity: { in: ['create', 'update', 'delete'] } }, exclusions: [] },
  { id: 'route-or-exit-node-enabled', behavior: 'control-modification', version: '1.0.0', title: 'Network route or exit node enabled', kind: 'event', severity: 'high', enabled: true, requirements: { all: ['configuration_change', 'route'] }, selector: { category: 'configuration', class: 'route_activity', activity: { in: ['enable', 'approve', 'advertise'] } }, exclusions: [] },
  { id: 'privileged-role-granted', behavior: 'privilege-escalation', version: '1.1.0', title: 'Privileged role granted', kind: 'event', severity: 'high', enabled: true, requirements: { oneOf: [['privilege_use', 'privilege_inventory']], optional: ['configuration_change'] }, selector: { category: 'identity', class: 'group_management', activity: { in: ['add_admin', 'grant_privilege', 'role_assign'] } }, exclusions: [] },
  { id: 'mfa-protection-disabled', behavior: 'credential-abuse', version: '1.0.0', title: 'Multi-factor protection disabled', kind: 'event', severity: 'high', enabled: true, requirements: { all: ['configuration_change'] }, selector: { category: 'identity', class: 'authentication_factor_activity', activity: { in: ['disable', 'delete'] } }, exclusions: [] },
  { id: 'credential-created', behavior: 'persistence', version: '1.1.0', title: 'Long-lived credential added or changed', kind: 'event', severity: 'medium', enabled: true, requirements: { oneOf: [['configuration_change', 'credential_inventory']] }, selector: { category: 'identity', class: 'credential_management', activity: { in: ['create_key', 'create_token', 'add_credential', 'update_credential', 'delete_credential'] } }, exclusions: [] },
  { id: 'privileged-ssh-credential-changed', behavior: 'persistence', version: '1.0.0', title: 'SSH credential changed for a privileged account', kind: 'event', severity: 'high', enabled: true, requirements: { all: ['credential_inventory', 'privilege_inventory'] }, selector: { category: 'identity', class: 'credential_management', activity: { in: ['add_credential', 'update_credential'] }, 'attributes.credentialKind': 'ssh_authorized_keys', 'attributes.privilegedOwner': true }, exclusions: [] },
  { id: 'local-account-created', behavior: 'persistence', version: '1.0.0', title: 'New local account appeared', kind: 'event', severity: 'high', enabled: true, requirements: { all: ['identity_inventory'] }, selector: { category: 'identity', class: 'account_management', activity: 'create', 'attributes.loginEnabled': true }, exclusions: [] },
  { id: 'persistent-service-created', behavior: 'persistence', version: '1.0.0', title: 'New persistent system service appeared', kind: 'event', severity: 'medium', enabled: true, requirements: { all: ['service_inventory'] }, selector: { category: 'configuration', class: 'service_activity', activity: { in: ['create', 'enable'] } }, exclusions: [] },
  { id: 'new-or-unapproved-access', behavior: 'resource-access', version: '1.0.0', title: 'New or unapproved device or service accessed', kind: 'event', severity: 'high', enabled: true, selector: { category: { in: ['identity', 'network', 'application'] }, outcome: 'success', 'attributes.accessDecision': { in: ['new_device', 'unapproved_device', 'new_service', 'unapproved_service'] } }, exclusions: [] },
  { id: 'authorization-failure-burst', behavior: 'resource-access', version: '1.0.0', title: 'Repeated authorization failures', kind: 'threshold', severity: 'medium', enabled: true, requirements: { all: ['resource_access'] }, selector: { class: 'authorization', outcome: 'failure' }, threshold: 20, windowSeconds: 300, groupBy: ['actor.id', 'service.name'], exclusions: [] },
  { id: 'resource-enumeration', behavior: 'resource-access', version: '1.0.0', title: 'Identity accesses many distinct resources', kind: 'threshold', severity: 'medium', enabled: true, requirements: { all: ['resource_access'] }, selector: { class: 'resource_access', outcome: 'success', 'actor.id': { exists: true }, 'attributes.resourceId': { exists: true } }, threshold: 50, distinctBy: 'attributes.resourceId', windowSeconds: 600, groupBy: ['actor.id', 'service.name'], exclusions: [] },
  { id: 'large-egress-transfer', behavior: 'data-exfiltration', version: '1.0.0', title: 'Large outbound data transfer', kind: 'event', severity: 'high', enabled: true, requirements: { all: ['network_flow'] }, selector: { category: 'network', class: 'network_activity', 'attributes.bytesSent': { gte: 2000000000 } }, exclusions: [] },
  { id: 'dns-failure-burst', behavior: 'command-and-control', version: '1.0.0', title: 'Burst of failed DNS queries', kind: 'threshold', severity: 'medium', enabled: true, requirements: { all: ['dns'] }, selector: { class: 'dns_activity', outcome: 'failure' }, threshold: 30, windowSeconds: 300, groupBy: ['sourceEndpoint.id'], exclusions: [] },
  { id: 'network-destination-scan', behavior: 'discovery', version: '1.1.0', title: 'Source contacts many distinct destinations', kind: 'threshold', severity: 'medium', enabled: true, requirements: { all: ['network_flow'] }, selector: { category: 'network', class: 'network_activity', 'destinationEndpoint.id': { exists: true } }, threshold: 5, distinctBy: 'destinationEndpoint.id', windowSeconds: 120, groupBy: ['sourceEndpoint.id'], exclusions: [] },
  { id: 'backup-protection-disabled', behavior: 'impact', version: '1.0.0', title: 'Backup protection disabled', kind: 'event', severity: 'high', enabled: true, requirements: { all: ['configuration_change'] }, selector: { category: 'configuration', class: 'backup_activity', activity: { in: ['disable', 'delete', 'retention_reduce'] } }, exclusions: [] },
  { id: 'public-share-created', behavior: 'data-exposure', version: '1.0.0', title: 'Public or external share created', kind: 'event', severity: 'high', enabled: true, requirements: { all: ['configuration_change', 'resource_access'] }, selector: { category: 'configuration', class: 'sharing_activity', activity: { in: ['public_create', 'external_create'] } }, exclusions: [] },
  { id: 'data-staging-then-egress', behavior: 'data-exfiltration', version: '1.0.0', title: 'Data staging followed by outbound transfer', kind: 'sequence', severity: 'critical', enabled: true, requirements: { all: ['file_access', 'network_flow'], optional: ['process_execution'] }, sequence: [{ category: 'data', class: 'archive_activity', activity: 'create' }, { category: 'network', class: 'network_activity', 'attributes.bytesSent': { gte: 100000000 } }], windowSeconds: 900, groupBy: ['sourceEndpoint.id'], exclusions: [] },
  { id: 'network-listener-created', behavior: 'service-exploitation', version: '1.0.0', title: 'New network-listening service appeared', kind: 'event', severity: 'high', enabled: true, requirements: { all: ['network_listener'] }, selector: { category: 'configuration', class: 'exposure_activity', activity: 'listener_create', 'attributes.exposureScope': { in: ['all_interfaces', 'host_interface'] } }, exclusions: [] },
  { id: 'security-control-disabled', behavior: 'defense-evasion', version: '1.0.0', title: 'Host security control stopped', kind: 'event', severity: 'high', enabled: true, requirements: { all: ['control_state'] }, selector: { category: 'configuration', class: 'security_control_activity', activity: 'disable' }, exclusions: [] },
  { id: 'sensitive-resource-created', behavior: 'resource-access', version: '1.0.0', title: 'New potentially sensitive data resource appeared', kind: 'event', severity: 'medium', enabled: true, requirements: { all: ['data_resource_inventory'] }, selector: { category: 'data', class: 'resource_activity', activity: 'create' }, exclusions: [] }
];

module.exports = { analytics: attachFrameworkMappings(analytics) };
